### ISSUE TITLE
[ERROR] "invalid literal for int() with base 10: 'checkpoints'" error when generating the balanced MotionSense's view with Preprocess_MotionSense.ipynb

### ISSUE THREAD

**Issue by joaoppagnan** [otavioon/librep-hiaac#11]
**Describe the bug:**

When generating MotionSense's balanced view with notebooks/datasets_preprocessing/Preprocess_MotionSense.ipynb the "invalid literal for int() with base 10: 'checkpoints'" error occurs in the third code block.

**To Reproduce:**

Run the notebook Preprocess_MotionSense.ipynb in the **resampled_motionsense_evaluation** branch. 

**Expected behavior:**

The notebook should run without this error and the balanced view should be generated.

**Desktop:**

    OS: Ubuntu 20.04

**Some solutions:**

This error occurs in line 89 of librep/datasets/har/motionsense.py, so the bug probably is in this script.

**Comment by otavioon** [comment]
Hello, @joaoppagnan. Thanks for describing the bug.

I've checked the notebook and the error message and it appears that, inside `A_DeviceMotion_data` directory (or any subdirectories), there is a folder named `checkpoints`, that should not be there. 
Can you please confirm it? If it is true, just remove this directory. Inside `datasets` directories should not have any other files, instead of dataset files. `.checkpoints` directory is usually generated when opening CSVs with `jupyter-lab`. 

One solution may be skip hidden folder inside `datasets`directory. This may be done filtering [the files found after glob](https://github.com/otavioon/librep-hiaac/blob/eda4d08a1249ed0e6d15fcff1b3a03f97d18d322/librep/datasets/har/motionsense.py#L80) at generators code. 

At.te.,
Otávio Napoli

**Comment by joaoppagnan** [comment]
Hello, @otavioon, thanks for the response.

I've checked if there is a subfolder named `./checkpoints` in this repo in the mentioned branch and there isn't. The following image show the results of the search: [grep and ls search](https://imgur.com/a/xTqfFiL)

Att.,
João Pagnan

**Comment by joaoppagnan** [comment]
@otavioon, I've run the `find` comand, deleted all the folders that have **checkpoints** (which were only the `.ipynb_checkpoints/` ones) and the error still persists.

Att.,
João Pagnan

**Comment by joaoppagnan** [comment]
@otavioon, the error stopped happening and the view is being generated normally.

Att.,
João Pagnan
